### ISSUE TITLE
Mobile button safari

### ISSUE THREAD

**Issue by guanacone** [guanacone/herotec.ca#2]
Button is not displayed properly in safari mobile. No idea why!
![Screenshot_20210523-112913_Chrome](https://user-images.githubusercontent.com/11678477/119271068-2a6e0b00-bbbd-11eb-8808-1c5e0debabdf.jpg)
![IMG-20210523-WA0001](https://user-images.githubusercontent.com/11678477/119271130-6acd8900-bbbd-11eb-88de-01e26304cf30.jpg)

**Comment by IsaacQiao** [comment]
try to [inspect](https://www.browserstack.com/guide/how-to-debug-on-iphone) iPhone browser if you have a mac

flex might not work for button on iOS
check these links out~
[The button element, and a couple other elements for that matter, cannot be flex containers in some browsers. Safari is one of them.](https://stackoverflow.com/questions/44301065/button-with-display-flex-does-not-work-in-safari-causing-size-and-alignment-is)
simple [fix](https://stackoverflow.com/a/35466231)

**Comment by edwmurph** [comment]
Wow that's an interesting one. I've never hit that before. I guess the fix you linked of putting the button content inside a span is a fine solution for now

It works in chrome today tho so for a longer term solution I'm hoping all the other browsers eventually get up to speed so we don't have to worry about this

**Comment by guanacone** [comment]
After inspecting the button on my gf iphone on her mac, I discovered that iOS applies some wired padding to the button. Setting `padding: 0` on the `<button>` solved the issue!
![WhatsApp Image 2021-05-24 at 08 09 25](https://user-images.githubusercontent.com/11678477/119360290-b2a8ea80-bc67-11eb-866e-2b88aad85b71.jpeg)

**Comment by edwmurph** [comment]
oh ok ya that works!

also nbd but just realized this is a public repo. would you mind making it private while we collaborate on it?
